### ISSUE TITLE
Arr full outer joins supported?

### ISSUE THREAD

**Issue by caderoux** [ili101/Join-Object#1]
If yes, what does this error mean?

Exception calling "SingleOrDefault" with "1" argument(s): "Sequence contains more than one element"
At C:\Program Files\WindowsPowerShell\Modules\Join-Object\0.1.6\Join-Object.ps1:556 char:17
+ ...             $RightLine = [System.Linq.Enumerable]::SingleOrDefault($R ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

**Comment by ili101** [comment]
Hi
Sorry for not updating this in a while, The master version in here do not support full outer join right now.
The Beta branch version have "-Type AllInBoth" support and some other additional functionality but it's not fully polished so I didn't uploaded it to master.

You can try the Beta version and update me if it works for you.

I also plan to do some code rewrite to simplify the code as it is written now almost every switch I add require to create another copy of main scriptblock that make it hard to manage.

Regarding the error "SingleOrDefault" this happens when your data have multiple records with the same JoinProperty (Key), what do you want the code to do in this situation? What I have now in Beta is:

1. Duplicate the line SQL stile? (There is a "MultiLeft" switch that do that for the Left side).
2. Make a sub Table in a new column? It's hard to Print Out and not compatible with SQL/Excel but very comfortable to loop on in your code (There is a "RightAsGroup" switch that do that for the Right side) but as I remember its not compatible with "AllInBoth".

What do you need it to do? maybe I will add it in the rewrite.

**Comment by caderoux** [comment]
There shouldn't be any duplicates, let me review.  The Key is supposed to be unique because it's a combination of properties already used in a Group-Object.

**Comment by caderoux** [comment]
I think you are right - the data changed and I now had TFS items in multiple iterations in a nested structure and I didn't include the Iteration Path in the key because it was unique before.  I still need the full outer join concept, though.

**Comment by ili101** [comment]
Install the Beta version by running this command:
```PowerShell
$Uri = 'https://raw.githubusercontent.com/ili101/Join-Object/Beta/Install.ps1'; & ([Scriptblock]::Create((irm $Uri))) -FromGitHub $Uri
```
And use "-Type AllInBoth"

**Comment by ili101** [comment]
I finished the rewrite. The new version has been released to the PowerShell Gallery.
you can get it from there `Install-Module -Name Join-Object -Scope CurrentUser`
